### ISSUE TITLE
ideal gas law is not found

### ISSUE THREAD

**Issue by physikerwelt** [ag-gipp/PhysWikiQuiz#4]
![Screenshot from 2021-08-30 09-01-11](https://user-images.githubusercontent.com/2777736/131298908-f509e348-db27-4356-981e-6ef72612c754.png)
![Screenshot from 2021-08-30 09-01-51](https://user-images.githubusercontent.com/2777736/131298958-dc458458-f80a-42bd-9372-8d0b779bca28.png)

**Comment by philsMINT** [comment]
composite (product) left-hand side PV is the problem

**Comment by physikerwelt** [comment]
![Screenshot 2021-09-03 at 09-29-32 PhysWikiQuiz](https://user-images.githubusercontent.com/2777736/131967483-b70aaf08-e31c-48b6-bd6a-ffd4764332a9.png)


> composite (product) left-hand side PV is the problem

can you explain further?

**Comment by philsMINT** [comment]
there is no single left-hand side variable, such as pressure P or volume V to query the student but a product PV instead. this is not supported because there is no name for the product

**Comment by philsMINT** [comment]
Hi Moritz,

ich bin nochmal alle Benchmark-Beispiele durchgegangen und habe sichergestellt, dass beim Feedback kein „Unknown Error“ mehr kommt.

Beste Grüße
Philipp

Von: Moritz Schubotz
Gesendet: Freitag, 3. September 2021 09:30
An: ag-gipp/PhysWikiQuiz
Cc: philsMINT; State change
Betreff: Re: [ag-gipp/PhysWikiQuiz] ideal gas law is not found (#4)

Reopened #4.
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
